# Generated by Django 5.0.2 on 2024-02-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmove',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmove',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
