# Generated by Django 5.0.2 on 2024-02-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarStatus',
            new_name='CarStatu',
        ),
    ]
