# Generated by Django 5.0.2 on 2024-02-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_carstatus_carstatu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarStatu',
        ),
    ]
